version: '3.9'  # upgrade to 3.9 when available, depends_on with condition problematic in some v3 versions
services:
    renderer:
        image: tomfumb/bvnordic-osm-renderer:1
        build:
            context: ../
            dockerfile: ./docker/renderer/Dockerfile
        depends_on:
            postgis:
                condition: service_healthy
        volumes:
            - source: ../../../output
              target: /output
              type: bind
    postgis:
        image: postgis/postgis:14-3.1
        environment:
            POSTGRES_PASSWORD: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 2s
            timeout: 2s
            retries: 5
