name: Export PDFs

on:
  push:
    branches:
      - '**'

jobs:
  generate:
    name: Generate Outputs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Directory Creator
      id: dir_create
      run: |
        . scripts/create-dir.sh
        ::set-output name=EXPORT_DIR::$(echo ${EXPORT_DIR})
    - name: Layout Generator
      run: |
        OUTPUT_BASE=/export/${{ steps.dir_create.outputs.EXPORT_DIR }} scripts/generate.sh
