name: Export PDFs

on:
  push:
    branches:
      - '**'

jobs:
  directory:
    name: Define Output Directory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Define
        run: |
          . scripts/directory.sh
          echo ${UNIQUE_DIR} > unique.dir
          echo ${LOCAL_OUTPUT_DIR} > local-output.dir
          echo ${CONTAINER_OUTPUT_DIR} > container-output.dir
      - name: Retain Directory Data
        uses: actions/upload-artifact@v2
        with:
          name: dirs
          path: '*.dir'

  layouts:
    name: Generate Layouts
    needs: directory
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Retrieve Directory Data
      uses: actions/download-artifact@v2
      with:
        name: dirs
    - name: Read to Var
      id: read_to_var
      run: |
        echo "::set-output name=LOCAL_OUTPUT_DIR::$(head -n 1 local-output.dir)"
        echo "::set-output name=CONTAINER_OUTPUT_DIR::$(head -n 1 container-output.dir)"
    - name: Layout Generator
      run: |
        mkdir -p ${{ steps.read_to_var.outputs.LOCAL_OUTPUT_DIR }}
        OUTPUT_BASE=${{ steps.read_to_var.outputs.CONTAINER_OUTPUT_DIR }} scripts/generate.sh
    - name: Retain Generated Layouts
      uses: actions/upload-artifact@v2
      with:
        name: outputs
        path: ${{ steps.read_to_var.outputs.LOCAL_OUTPUT_DIR }}/

  upload:
    name: Upload Layouts
    needs: layouts
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Directory Data
        uses: actions/download-artifact@v2
        with:
          name: dirs
      - name: Retrieve Generated Layouts
        uses: actions/download-artifact@v2
        with:
          name: outputs
      - name: Read to Var
        id: read_to_var
        run: |
          echo "::set-output name=UNIQUE_DIR::$(head -n 1 unique.dir)"
          echo "::set-output name=LOCAL_OUTPUT_DIR::$(head -n 1 local-output.dir)"
      - name: debugger
        run: |
          ls -Alh
      - name: Upload to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: ${{ steps.read_to_var.outputs.UNIQUE_DIR }}
          credentials: ${{ secrets.GDRIVE_UPLOAD_SERVICE_ACCT_KEY }}
          folder: 1asRtVzDgiL__LobxbZUTHZx-sNEDMGg6