name: Export PDFs

on:
  push:
    branches:
      - '**'

jobs:
  directory:
    name: Define Output Directory
    runs-on: ubuntu-latest
    steps:
      - name: execute
        run: |
          . scripts/directory.sh
          echo ${LOCAL_DIR} > local.dir
          echo ${CONTAINER_DIR} > container.dir
          echo "### LOCAL"
          cat local.dir
          echo "### CONTAINER"
          cat container.dir
          echo "### CURRENT"
          pwd
      - name: Retain Directory Data (Container)
        uses: actions/upload-artifact@v2
        with:
          name: dirs
          path: '*.dir'

  layouts:
    name: Generate Layouts
    needs: directory
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Retrieve Directory Data (Container)
      uses: actions/download-artifact@v2
      with:
        name: dirs
    - name: Layout Generator
      run: |
        echo "### LOCAL"
        cat local.dir
        echo "### CONTAINER"
        cat container.dir
        mkdir -p $(head -n 1 local.dir)
        OUTPUT_BASE=$(head -n 1 container.dir) scripts/generate.sh
