name: Visual diff for PRs

on:
  pull_request:
    branches:
      - '**'

jobs:

  pr_pending:
    name: Show PR Pending
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Python Dependencies
        run: |
          pip install -r cicd/compare/requirements-pr.txt
      - name: Execute Python
        run: |
          python -m cicd.compare.pr.show_pending $GITHUB_REPOSITORY $GITHUB_REF
        env:
          PAT_GITHUB_API: ${{ secrets.PAT_GITHUB_API }}

  define_shas:
    name: Define SHAs for Compare
    needs: pr_pending
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Python Dependencies
        run: |
          pip install -r cicd/compare/requirements-pr.txt
      - name: Execute Python
        run: |
          python -m cicd.compare.pr.get_shas $GITHUB_REPOSITORY $GITHUB_REF
      - name: Retain SHAs
        uses: actions/upload-artifact@v2
        with:
          name: shas
          path: cicd/compare/pr/shas.txt

  create_dirs:
    name: Create Required Directories
    needs: define_shas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve SHAs
        uses: actions/download-artifact@v2
        with:
          name: shas
      - name: Read to Var
        id: read_to_var_shas
        run: |
          echo "::set-output name=PR_SHA1::$(head -n 1 shas.txt)"
          echo "::set-output name=PR_SHA2::$(head -n 2 shas.txt | tail -n 1)"
      - name: Create Directories
        run: |
          . cicd/compare/scripts/create_directories.sh before=${{ steps.read_to_var_shas.outputs.PR_SHA1 }} after=${{ steps.read_to_var_shas.outputs.PR_SHA2 }}
          echo $COMPARE_DIR > compare.dir
          echo $OUTPUT_BASE > output-base.dir
      - name: Retain Directory Data
        uses: actions/upload-artifact@v2
        with:
          name: dirs
          path: '*.dir'

  compare:
    name: Perform Image Comparison
    needs: create_dirs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # required to check out older versions for comparison
      - name: Retrieve SHAs
        uses: actions/download-artifact@v2
        with:
          name: shas
      - name: Read to Var
        id: read_to_var_shas
        run: |
          echo "::set-output name=PR_SHA1::$(head -n 1 shas.txt)"
          echo "::set-output name=PR_SHA2::$(head -n 2 shas.txt | tail -n 1)"
      - name: Validate Comparison
        run: |
          cicd/compare/scripts/check_comparable.sh before=${{ steps.read_to_var_shas.outputs.PR_SHA1 }} after=${{ steps.read_to_var_shas.outputs.PR_SHA2 }}
      - name: Retrieve Dirs
        uses: actions/download-artifact@v2
        with:
          name: dirs
      - name: Read to Var
        id: read_to_var_dirs
        run: |
          echo "::set-output name=COMPARE_DIR::$(head -n 1 compare.dir)"
          echo "::set-output name=OUTPUT_BASE::$(head -n 1 output-base.dir)"
      - name: Create Directories
        run: |
          mkdir -p ${{ steps.read_to_var_dirs.outputs.OUTPUT_BASE }}/${{ steps.read_to_var_shas.outputs.PR_SHA1 }}
          mkdir -p ${{ steps.read_to_var_dirs.outputs.OUTPUT_BASE }}/${{ steps.read_to_var_shas.outputs.PR_SHA2 }}
      - name: Generate Exports
        run: |
          docker build -t exporter cicd/export/docker
          docker run --rm -v $PWD:/code exporter /code/cicd/export/docker/generate_revision.sh output_base=/code/${{ steps.read_to_var_dirs.outputs.OUTPUT_BASE }}/${{ steps.read_to_var_shas.outputs.PR_SHA1 }} revision=${{ steps.read_to_var_shas.outputs.PR_SHA1 }} png=1
          docker run --rm -v $PWD:/code exporter /code/cicd/export/docker/generate_revision.sh output_base=/code/${{ steps.read_to_var_dirs.outputs.OUTPUT_BASE }}/${{ steps.read_to_var_shas.outputs.PR_SHA1 }} revision=${{ steps.read_to_var_shas.outputs.PR_SHA1 }} png=1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Python Dependencies
        run: |
          pip install -r cicd/compare/requirements-detect.txt
      - name: debug
        run: |
          ls -AlhR output
      - name: Detect Changes
        run: |
          python -m cicd.compare.detect_changes ${{ steps.read_to_var_shas.outputs.PR_SHA1 }} ${{ steps.read_to_var_shas.outputs.PR_SHA2 }} $PWD/${{ steps.read_to_var_dirs.outputs.OUTPUT_BASE }}
      - name: debug
        run: |
          ls -AlhR output
      - name: Remove Unnecessary Files
        run: |
          sudo rm -rf ${{ steps.read_to_var_dirs.outputs.OUTPUT_BASE }}/${{ steps.read_to_var_shas.outputs.PR_SHA1 }}
          sudo rm -rf ${{ steps.read_to_var_dirs.outputs.OUTPUT_BASE }}/${{ steps.read_to_var_shas.outputs.PR_SHA2 }}
      - name: Bundle Changes
        uses: papeloto/action-zip@v1
        with:
          files: output
          dest: output.zip
      - name: Retain Changes
        uses: actions/upload-artifact@v2
        with:
          name: changes
          path: output.zip

  upload:
    name: Upload
    needs: compare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve Dirs
        uses: actions/download-artifact@v2
        with:
          name: dirs
      - name: Read to Var
        id: read_to_var_dirs
        run: |
          echo "::set-output name=COMPARE_DIR::$(head -n 1 compare.dir)"
          echo "::set-output name=OUTPUT_BASE::$(head -n 1 output-base.dir)"
      - name: Retrieve Bundle
        uses: actions/download-artifact@v2
        with:
          name: changes
      - name: Unpack Bundle
        run: |
          rm -rf output
          unzip -d output output.zip
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Python Dependencies
        run: |
          pip install -r cicd/upload/requirements.txt
      - name: Upload to Google Drive
        run: |
          python -m cicd.upload.upload ${{ steps.read_to_var_dirs.outputs.COMPARE_DIR }} $PWD/output
        env:
          GDRIVE_UPLOAD_SERVICE_ACCT_INFO: ${{ secrets.GDRIVE_PR_UPLOAD_SERVICE_ACCT_INFO }}

  update_pr:
    name: Update PR
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve Dirs
        uses: actions/download-artifact@v2
        with:
          name: dirs
      - name: Read to Var
        id: read_to_var_dirs
        run: |
          echo "::set-output name=COMPARE_DIR::$(head -n 1 compare.dir)"
          echo "::set-output name=OUTPUT_BASE::$(head -n 1 output-base.dir)"
      - name: Retrieve Changes
        uses: actions/download-artifact@v2
        with:
          name: changes
      - name: Unpack Bundle
        run: |
          rm -rf output
          unzip -d output output.zip
      - name: debug dir content
        run: |
          ls -AlhR
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Python Dependencies
        run: |
          pip install -r cicd/compare/requirements-pr.txt
      - name: Execute Python
        run: |
          python -m cicd.compare.pr.show_changes $GITHUB_REPOSITORY $GITHUB_REF ${{ steps.read_to_var_dirs.outputs.OUTPUT_BASE }}/result/changes.json ${{ steps.read_to_var_dirs.outputs.OUTPUT_BASE }}/uploads.json
        env:
          PAT_GITHUB_API: ${{ secrets.PAT_GITHUB_API }}
